steps:
  # build the container images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA', '.']

  #push the container image to artifact registry
  - name: 'gcr.io/could-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA']

  #deploy container image to cloud run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - 'deploy'
      - 'demo-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
    images:
      - 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA'